#!/bin/bash

# Function to display information about a subdomain
display_info() {
    local subdomain=$1
    local domain=$2
    local record_type=$(dig +short -t A ${subdomain}.${domain})
    local destination=$(dig +short ${subdomain}.${domain})
    
    if [ -z "$record_type" ]; then
        echo "The subdomain $subdomain is not configured."
    else
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

# Check if both domain and subdomain parameters are provided
if [ "$#" -eq 2 ]; then
    display_info "$2" "$1"
else
    # Default subdomains to check
    subdomains=("www" "lb-01" "web-01" "web-02")
    
    for subdomain in "${subdomains[@]}"; do
        display_info "$subdomain" "$1"
    done
fi

