#!/usr/bin/env bash
# Script to display the PID and process name of processes containing the word 'bash'
# Note: In this script, 'pgrep' is used instead of 'ps' for simplicity and brevity.
# Use 'pgrep' to find processes with the name 'bash' and display their PIDs along with process names
pgrep -l bash

